from class_lista import Lista

print('To Do List')
l=Lista('Lista_ToDo')
l.a('primo')
l.a('secondo')
l.a('terzo')
print('mostra elementi inseriti')
l.ls()
l.e('1','secondanza')
print('mostra elementi dopo modifica')
l.ls()
l.d('2')
print('mostra  elementi dopo eliminazione')
l.ls()
l.t('1')
print('mostra elementi dopo toggle')
l.ls()
print('ricerca elemento presente')
l.s('primo')
print('ricerca elemento non presente')
l.s('quarto')
